version: "3.9"
services:
  db:
    image: bitnine/agensgraph:latest          # PostgreSQL + AGE/Cypher
    environment:
      POSTGRES_PASSWORD: agenspw
    ports: 
      - "5432:5432"
    volumes:
      - agensgraph_data:/var/lib/postgresql/data

  api:
    build: ./api                            # Express + TS
    environment:
      DB_HOST: db
      DB_PASS: agenspw
      DB_USER: postgres
      DB_PORT: 5432
    ports: 
      - "4000:4000"
    depends_on: 
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: ./web                            # React 18 + Vite
    ports: 
      - "5173:5173"
    environment:
      VITE_API_ORIGIN: http://localhost:4000
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  agensgraph_data: